// Spanish strings. Same keys as strings.en.js; keep every {placeholder}.
// Demo copy only: no clinical guidance. Should be checked by a native speaker
// before the demo (PRD open question 3).

export default {
  lang: "es",
  language_name: "Español",

  // Shared
  prototype_footer: "Prototipo, no apto para uso clínico.",
  prototype_footer_detail: "Solo usuarios de demostración y datos ficticios. Nunca lo conecte a una persona.",
  simulated_data: "Datos simulados",
  skip_to_content: "Ir al contenido principal",
  loading: "Cargando…",
  unit_ml_hr: "{value} mL/h",
  unit_ml: "{value} mL",
  version: "Versión {version}",
  updated_at: "Última actualización {time}",
  never_updated: "Aún no hay datos de la bomba",

  // Connection
  pump_online: "Bomba conectada",
  pump_offline: "Bomba sin conexión",
  pump_offline_since: "Bomba sin conexión desde las {time}",
  pump_offline_body: "La bomba sigue funcionando con los últimos ajustes aceptados. Los datos aparecerán aquí cuando vuelva a conectarse.",
  hub_lost: "Se perdió el contacto con el centro de casa. Reintentando…",
  offline_last_update: "Sin conexión, última actualización {time}",
  offline_no_update: "Sin conexión, aún sin datos",
  connecting: "Conectando con el centro de casa…",
  online_last_update: "Bomba conectada. Última actualización {time}",

  // Settings
  night_mode: "Modo noche",

  // Pump states
  state_idle: "Lista, sin alimentar",
  state_priming: "Preparando",
  state_running: "Alimentando",
  state_paused: "En pausa",
  state_alarm: "Necesita atención",
  state_complete: "Alimentación terminada",

  // Alarms
  alarm_occlusion: "Tubo bloqueado",
  alarm_bag_empty: "Bolsa vacía",
  alarm_low_battery: "Batería baja",
  alarm_sensor_mismatch: "El nivel de la bolsa no coincide",
  alarm_line: "Alarma: {alarm}. Revise la bomba.",

  // Prescription fields
  field_mode: "Modo",
  field_rate: "Velocidad",
  field_volume: "Volumen de la toma",
  field_note: "Nota",
  mode_continuous: "Continuo",
  mode_bolus: "Bolo",

  // Prescription chip
  rx_proposed: "Pendiente",
  rx_proposed_detail: "Esperando la confirmación del cuidador",
  rx_confirmed: "Pendiente",
  rx_confirmed_detail: "Confirmado, enviando a la bomba",
  rx_sent: "Enviado",
  rx_sent_detail: "Esperando que la bomba lo informe",
  rx_sent_offline: "Enviado: bomba sin conexión desde las {time}",
  rx_active: "Activo en la bomba",
  rx_active_detail: "La bomba informó esta versión",
  rx_rejected: "Rechazado",
  rx_rejected_reason: "Rechazado: {reason}",
  rx_superseded: "Reemplazado",
  rx_superseded_detail: "Una versión más nueva reemplazó a esta",

  // Reject reasons
  reason_rate_out_of_range: "velocidad fuera de rango",
  reason_volume_out_of_range: "volumen fuera de rango",
  reason_not_confirmed: "sin confirmación del cuidador",
  reason_stale_version: "más antigua que la versión de la bomba",
  reason_malformed: "la bomba no pudo leerlo",
  reason_wrong_pump: "enviado a otra bomba",
  reason_declined: "rechazado por el cuidador",

  // API errors
  error_invalid_input: "Faltan datos o no son válidos. Revise el formulario.",
  error_not_proposed: "Este cambio ya fue respondido.",
  error_unknown_pump: "El centro no conoce esta bomba.",
  error_network: "No se pudo contactar con el centro de casa. Revise la conexión e inténtelo de nuevo.",
  error_generic: "Algo salió mal. Inténtelo de nuevo.",

  // Family app
  family_title: "Bomba de alimentación",
  family_page_title: "Bomba de alimentación (prototipo)",
  family_today: "Hoy",
  family_delivered: "Administrado",
  family_of_target: "{delivered} de {target}",
  family_progress_label: "Progreso de la toma",
  family_rate_now: "Velocidad actual",
  family_no_feed: "Aún no hay toma programada",
  family_status_spoken: "{state}. {delivered} de {target} administrados.",
  family_caregiver: "¿Quién usa este teléfono?",
  role_parent: "Madre o padre (demo)",
  role_school_nurse: "Enfermería escolar (demo)",

  review_title: "Cambio para revisar",
  review_intro: "{clinician} pidió cambiar la alimentación. Nada cambia hasta que usted confirme.",
  review_now: "Ahora",
  review_new: "Nuevo",
  review_changed: "Cambia",
  review_same: "Igual",
  review_note: "Nota del profesional",
  review_confirm: "Confirmar cambio",
  review_decline: "Rechazar",
  review_working: "Enviando…",
  review_sent: "Confirmado. Enviado a la bomba. Esperando que la bomba lo informe.",
  review_active: "Listo. La bomba ahora usa la versión {version}.",
  review_rejected: "La bomba rechazó este cambio: {reason}. Los ajustes de la bomba no cambiaron.",
  review_declined: "Usted rechazó este cambio. Los ajustes de la bomba no cambiaron.",
  review_queued_hint: "Si hay una toma en curso, la bomba espera a que termine antes de cambiar.",
  review_none: "No hay cambios pendientes.",
  review_who: "Confirma",
  review_waiting: "Hay un cambio esperando su revisión.",
  review_pending: "Pendiente. Esperando al centro de casa.",
  review_superseded: "Un cambio más nuevo reemplazó a este.",
  review_ok: "Entendido",
  review_outcome_title: "Su última respuesta",
  review_version: "Cambio a la versión {version}",
  waiting_for_pump: "Esperando a la bomba",

  // Clinician portal
  clin_title: "Portal clínico",
  clin_page_title: "Portal clínico (prototipo)",
  clin_user: "Sesión de Dr. Demo (usuario de demostración, sin inicio de sesión real)",
  clin_patient: "Paciente",
  clin_pump: "Bomba {pump}",
  clin_live: "Bomba ahora",
  clin_state: "Estado",
  clin_active_version: "Versión activa",
  clin_none: "Ninguna",
  clin_propose_title: "Proponer un cambio",
  clin_propose_intro: "El cuidador debe confirmarlo. La bomba comprueba sus propios límites y puede rechazarlo.",
  clin_rate_hint: "Mililitros por hora",
  clin_volume_hint: "Total de una toma, en mililitros",
  clin_note_hint: "Opcional. Hasta 200 caracteres. Quedan {left}.",
  clin_submit: "Proponer cambio",
  clin_submitting: "Proponiendo…",
  clin_proposed_ok: "Versión {version} propuesta. Esperando al cuidador.",
  clin_history_title: "Prescripciones",
  clin_history_empty: "Aún no hay prescripciones.",
  clin_proposed_by: "Propuesta {time}",
  clin_confirmed_by: "Confirmada por {who}",
  clin_chip_announce: "Versión {version}: {label}",
  clin_summary: "{mode}, {rate}, {volume}",
  clin_time_proposed: "Propuesta {time}",
  clin_time_sent: "Enviada {time}",
  clin_time_resolved: "La bomba respondió {time}",
  clin_values_heading: "Versión {version}",
  clin_form_errors: "El formulario tiene problemas",

  val_required: "Escriba un valor.",
  val_positive: "Escriba un número mayor que 0.",
  val_mode: "Elija un modo.",
  val_note_long: "La nota debe tener 200 caracteres o menos.",
  val_fix: "Corrija {count} problema(s) del formulario.",

  // Settings and language
  settings_title: "Ajustes",
  language_label: "Idioma",
  review_confirming_as: "Confirma: {who}.",
  review_change_who: "Puede cambiar quién usa este teléfono en Ajustes, más abajo.",

  // Alerts
  alerts_enable_title: "Activar alertas",
  alerts_enable_body: "Toque una vez para que este teléfono vibre, suene y hable cuando la bomba le necesite.",
  alerts_enable_btn: "Activar alertas",
  alerts_enabled: "Las alertas están activadas durante esta visita.",
  alert_what: "Qué pasó",
  alert_steps: "Qué hacer",
  alert_done: "Listo, ya lo revisé",
  alert_started: "Empezó a las {time}",
  alert_waiting: "Esperando a la bomba. Pulse Borrar en la bomba cuando el problema esté resuelto.",
  alert_cleared: "La alarma se borró en la bomba.",
  alert_spoken: "Alarma de la bomba. {alarm}. {cause}",
  cause_occlusion: "Algo está bloqueando el tubo de alimentación, por eso la bomba se detuvo.",
  cause_bag_empty: "La bolsa está vacía, por eso la bomba se detuvo.",
  cause_low_battery: "La batería de la bomba está baja.",
  cause_sensor_mismatch: "El nivel de la bolsa no coincide con lo que esperaba la bomba, por eso se detuvo.",
  steps_occlusion: [
    "Revise el tubo en busca de dobleces, nudos o una pinza cerrada.",
    "Enderece el tubo o abra la pinza.",
    "Pulse Borrar en la bomba.",
    "Si la alarma vuelve, llame a su equipo de atención.",
  ],
  steps_bag_empty: [
    "Revise la bolsa de alimentación.",
    "Siga el plan de su equipo de atención para una bolsa nueva.",
    "Pulse Borrar en la bomba.",
  ],
  steps_low_battery: [
    "Conecte la bomba a su cargador.",
    "Déjela conectada hasta que la batería esté llena.",
  ],
  steps_sensor_mismatch: [
    "Compruebe que la bolsa cuelga recta y que el tubo está conectado.",
    "Pulse Borrar en la bomba.",
    "Si la alarma vuelve, llame a su equipo de atención.",
  ],
  pic_occlusion: "Dibujo de un tubo de alimentación con un doblez",
  pic_bag_empty: "Dibujo de una bolsa de alimentación vacía",
  pic_low_battery: "Dibujo de una batería casi vacía",
  pic_sensor_mismatch: "Dibujo de una bolsa de alimentación con un signo de interrogación",

  // Alert preferences
  prefs_title: "Alertas para {who}",
  pref_vibrate: "Vibrar",
  pref_sound: "Sonido",
  pref_speak: "Leer las alertas en voz alta",

  // Voice
  speak_status: "Leer el estado en voz alta",
  voice_answer: "Responder por voz",
  voice_listening: "Escuchando. Diga «{yes}» o «{no}».",
  voice_yes_words: ["sí", "si", "confirmar"],
  voice_no_words: ["no", "rechazar"],
  voice_unheard: "No le entendí. Use los botones.",

  // Portal: patient list
  clin_patients_title: "Pacientes",
  clin_patients_intro: "Los pacientes que necesitan atención aparecen primero.",
  clin_open_patient: "Abrir",
  clin_current_patient: "En pantalla",
  exc_offline: "Bomba sin conexión",
  exc_under_target: "Por debajo del objetivo 3 días",
  exc_night_alarms: "Muchas alarmas nocturnas",
  exc_alarm: "Alarma ahora: {alarm}",
  exc_none: "Sin excepciones",
  clin_unavailable: "El centro aún no ofrece estos datos.",

  // Portal: chart
  chart_title: "Administrado frente a prescrito",
  range_label: "Periodo",
  range_24h: "24 h",
  range_7d: "7 días",
  range_30d: "30 días",
  chart_delivered: "Administrado",
  chart_prescribed: "Prescrito",
  chart_under: "Menos del 90 % de lo prescrito",
  chart_live_note: "24 h muestra las lecturas en vivo de la bomba en esta sesión.",
  chart_show_table: "Ver como tabla",
  chart_col_date: "Fecha",
  chart_col_time: "Hora",
  chart_col_alarms: "Alarmas",
  chart_desc: "Se muestran {days} días. {under} por debajo del 90 % de lo prescrito.",
  chart_live_desc: "Toma en vivo: {delivered} de {target} administrados.",
  chart_no_data: "Aún no hay datos.",
  chart_yes: "Sí",

  // Portal: alarm timeline
  timeline_title: "Historial de alarmas",
  timeline_empty: "No se han informado alarmas en esta sesión.",
  timeline_active: "Sigue activa",
  timeline_cleared: "Borrada a las {time}, tras {minutes} min",

  // Portal: audit
  audit_title: "Registro de auditoría",
  audit_col_when: "Cuándo",
  audit_col_who: "Quién",
  audit_col_what: "Qué",
  audit_col_version: "Versión",
  audit_empty: "Aún no hay entradas.",
  audit_who: "{name} ({role})",
  action_proposed: "Propuesta",
  action_confirmed: "Confirmada",
  action_declined: "Rechazada por el cuidador",
  action_sent: "Enviada a la bomba",
  action_active: "Activa en la bomba",
  action_rejected: "Rechazada",
  action_superseded: "Reemplazada",
  role_clinician: "Profesional clínico",
  role_system: "Centro",
  role_pump: "Bomba",

  // Portal: feed profiles
  profiles_title: "Perfiles de alimentación",
  profiles_intro: "Rellena el formulario. Solo valores de demostración, no son indicaciones.",
  profile_overnight: "Continuo nocturno",
  profile_day_bolus: "Bolo diurno",
  profile_school: "Día de escuela",
  profile_applied: "Formulario rellenado con «{name}». Revíselo y luego propóngalo.",

  // Sync 2 contract additions
  error_stale_version: "Ya se envió a la bomba un cambio más nuevo, así que este no se puede confirmar.",
  exc_alarm_active: "Alarma ahora",
  summary_title: "Resumen semanal",
  summary_range: "Del {from} al {to}",
  summary_delivered: "Se administró el {pct} % de lo prescrito en {days} días.",
  summary_prior: "Semana anterior: {pct} %.",
  trend_improving: "Tendencia: mejora",
  trend_steady: "Tendencia: estable",
  trend_declining: "Tendencia: empeora",
  summary_under: "Días por debajo del 90 % de lo prescrito: {count}.",
  summary_alarms: "Alarmas: {count} ({list}).",
  summary_no_alarms: "Sin alarmas esta semana.",
  summary_none: "Aún no hay historial.",
  profiles_none: "No hay perfiles de alimentación para este paciente.",

  users: {
    "clin-01": "Dr. Demo",
    "care-01": "Madre o padre (demo)",
    "care-02": "Enfermería escolar (demo)",
    pump: "Bomba",
    hub: "Centro",
  },
};
