// Every user-facing string, for both apps (FR-25). Add a language by copying
// this file to strings.<lang>.js and translating the values; keep the keys.
// {name} placeholders are filled in by t(). Demo copy only: no clinical guidance.

export default {
  lang: "en",
  language_name: "English",

  // Shared
  prototype_footer: "Prototype, not for clinical use.",
  prototype_footer_detail: "Demo users and fictional data only. Never connect to a person.",
  simulated_data: "Simulated data",
  skip_to_content: "Skip to main content",
  loading: "Loading…",
  unit_ml_hr: "{value} mL/hr",
  unit_ml: "{value} mL",
  version: "Version {version}",
  updated_at: "Last update {time}",
  never_updated: "No update from the pump yet",

  // Connection
  pump_online: "Pump connected",
  pump_offline: "Pump offline",
  pump_offline_since: "Pump offline since {time}",
  pump_offline_body: "The pump keeps running its last accepted settings. Updates will show here when it reconnects.",
  hub_lost: "Lost contact with the home hub. Trying again…",
  offline_last_update: "Offline, last update {time}",
  offline_no_update: "Offline, no update yet",
  connecting: "Connecting to the home hub…",
  online_last_update: "Pump connected. Last update {time}",

  // Settings
  night_mode: "Night mode",

  // Pump states
  state_idle: "Ready, not feeding",
  state_priming: "Getting ready",
  state_running: "Feeding",
  state_paused: "Paused",
  state_alarm: "Needs attention",
  state_complete: "Feed finished",

  // Alarms (short names; full alert screens come later)
  alarm_occlusion: "Tube blocked",
  alarm_bag_empty: "Bag empty",
  alarm_low_battery: "Battery low",
  alarm_sensor_mismatch: "Bag level does not match",
  alarm_line: "Alarm: {alarm}. Check the pump.",

  // Prescription fields
  field_mode: "Mode",
  field_rate: "Rate",
  field_volume: "Feed volume",
  field_note: "Note",
  mode_continuous: "Continuous",
  mode_bolus: "Bolus",

  // Prescription chip (exactly the hub's state, S5)
  rx_proposed: "Pending",
  rx_proposed_detail: "Waiting for the caregiver to confirm",
  rx_confirmed: "Pending",
  rx_confirmed_detail: "Confirmed, sending to pump",
  rx_sent: "Sent",
  rx_sent_detail: "Waiting for the pump to report it",
  rx_sent_offline: "Sent: pump offline since {time}",
  rx_active: "Active on pump",
  rx_active_detail: "The pump reported this version",
  rx_rejected: "Rejected",
  rx_rejected_reason: "Rejected: {reason}",
  rx_superseded: "Replaced",
  rx_superseded_detail: "A newer version replaced this one",

  // Reject reasons (pump reasons from event.schema.json, plus declined)
  reason_rate_out_of_range: "rate out of range",
  reason_volume_out_of_range: "volume out of range",
  reason_not_confirmed: "no caregiver confirmation",
  reason_stale_version: "older than the version on the pump",
  reason_malformed: "the pump could not read it",
  reason_wrong_pump: "sent to the wrong pump",
  reason_declined: "declined by caregiver",

  // API errors (codes from docs/API.md)
  error_invalid_input: "Some details are missing or not valid. Check the form.",
  error_not_proposed: "This change was already answered.",
  error_unknown_pump: "The hub does not know this pump.",
  error_network: "Could not reach the home hub. Check the connection and try again.",
  error_generic: "Something went wrong. Try again.",

  // Family app
  family_title: "Feeding pump",
  family_page_title: "Feeding pump (prototype)",
  family_today: "Today",
  family_delivered: "Delivered",
  family_of_target: "{delivered} of {target}",
  family_progress_label: "Feed progress",
  family_rate_now: "Rate now",
  family_no_feed: "No feed set yet",
  family_status_spoken: "{state}. {delivered} of {target} delivered.",
  family_caregiver: "Who is using this phone?",
  role_parent: "Parent (demo)",
  role_school_nurse: "School nurse (demo)",

  review_title: "Change to review",
  review_intro: "{clinician} asked to change the feed. Nothing changes until you confirm.",
  review_now: "Now",
  review_new: "New",
  review_changed: "Changed",
  review_same: "Same",
  review_note: "Note from the clinician",
  review_confirm: "Confirm change",
  review_decline: "Decline",
  review_working: "Sending…",
  review_sent: "Confirmed. Sent to the pump. Waiting for the pump to report it.",
  review_active: "Done. The pump is now using version {version}.",
  review_rejected: "The pump refused this change: {reason}. The pump settings did not change.",
  review_declined: "You declined this change. The pump settings did not change.",
  review_queued_hint: "If a feed is running, the pump waits until it finishes before changing.",
  review_none: "No changes waiting for you.",
  review_who: "Confirming as",
  review_waiting: "A change is waiting for your review.",
  review_pending: "Pending. Waiting for the home hub.",
  review_superseded: "A newer change replaced this one.",
  review_ok: "OK",
  review_outcome_title: "Your last answer",
  review_version: "Change to version {version}",
  waiting_for_pump: "Waiting for the pump",

  // Clinician portal
  clin_title: "Clinician portal",
  clin_page_title: "Clinician portal (prototype)",
  clin_user: "Signed in as Dr. Demo (demo user, no real login)",
  clin_patient: "Patient",
  clin_pump: "Pump {pump}",
  clin_live: "Pump now",
  clin_state: "State",
  clin_active_version: "Active version",
  clin_none: "None",
  clin_propose_title: "Propose a change",
  clin_propose_intro: "The caregiver must confirm it. The pump checks its own limits and may refuse it.",
  clin_rate_hint: "Millilitres per hour",
  clin_volume_hint: "Total for one feed, in millilitres",
  clin_note_hint: "Optional. Up to 200 characters. {left} left.",
  clin_submit: "Propose change",
  clin_submitting: "Proposing…",
  clin_proposed_ok: "Version {version} proposed. Waiting for the caregiver.",
  clin_history_title: "Prescriptions",
  clin_history_empty: "No prescriptions yet.",
  clin_proposed_by: "Proposed {time}",
  clin_confirmed_by: "Confirmed by {who}",
  clin_chip_announce: "Version {version}: {label}",
  clin_summary: "{mode}, {rate}, {volume}",
  clin_time_proposed: "Proposed {time}",
  clin_time_sent: "Sent {time}",
  clin_time_resolved: "Pump answered {time}",
  clin_values_heading: "Version {version}",
  clin_form_errors: "The form has problems",

  val_required: "Enter a value.",
  val_positive: "Enter a number greater than 0.",
  val_mode: "Choose a mode.",
  val_note_long: "Keep the note to 200 characters or fewer.",
  val_fix: "Fix {count} problem(s) in the form.",

  // Settings and language
  settings_title: "Settings",
  language_label: "Language",
  review_confirming_as: "Confirming as {who}.",
  review_change_who: "Change who is using this phone in Settings below.",

  // Alerts (FR-14). Device handling only, never clinical guidance.
  alerts_enable_title: "Turn on alerts",
  alerts_enable_body: "Tap once so this phone can vibrate, beep and speak when the pump needs you.",
  alerts_enable_btn: "Turn on alerts",
  alerts_enabled: "Alerts are on for this visit.",
  alert_what: "What happened",
  alert_steps: "What to do",
  alert_done: "Done, I have checked",
  alert_started: "Started {time}",
  alert_waiting: "Waiting for the pump. Press Clear on the pump when the problem is fixed.",
  alert_cleared: "The alarm was cleared at the pump.",
  alert_spoken: "Pump alarm. {alarm}. {cause}",
  cause_occlusion: "Something is blocking the feeding tube, so the pump stopped.",
  cause_bag_empty: "The feed bag is empty, so the pump stopped.",
  cause_low_battery: "The pump battery is low.",
  cause_sensor_mismatch: "The bag level does not match what the pump expected, so the pump stopped.",
  steps_occlusion: [
    "Look along the tube for a bend, kink or closed clamp.",
    "Straighten the tube or open the clamp.",
    "Press Clear on the pump.",
    "If the alarm comes back, call your care team.",
  ],
  steps_bag_empty: [
    "Check the feed bag.",
    "Follow your care team's plan for a new bag.",
    "Press Clear on the pump.",
  ],
  steps_low_battery: [
    "Plug the pump into its charger.",
    "Keep the charger connected until the battery is full.",
  ],
  steps_sensor_mismatch: [
    "Check that the bag is hanging straight and the tube is connected.",
    "Press Clear on the pump.",
    "If the alarm comes back, call your care team.",
  ],
  pic_occlusion: "Drawing of a feeding tube with a sharp bend in it",
  pic_bag_empty: "Drawing of an empty feed bag",
  pic_low_battery: "Drawing of a nearly empty battery",
  pic_sensor_mismatch: "Drawing of a feed bag with a question mark",

  // Alert preferences per caregiver (FR-29)
  prefs_title: "Alerts for {who}",
  pref_vibrate: "Vibrate",
  pref_sound: "Beep",
  pref_speak: "Speak alerts out loud",

  // Voice (FR-27, NFR-A5)
  speak_status: "Read status aloud",
  voice_answer: "Answer by voice",
  voice_listening: "Listening. Say “{yes}” or “{no}”.",
  voice_yes_words: ["yes", "confirm"],
  voice_no_words: ["no", "decline"],
  voice_unheard: "Did not catch that. Use the buttons.",

  // Portal: patient list (FR-19)
  clin_patients_title: "Patients",
  clin_patients_intro: "Patients who need attention are listed first.",
  clin_open_patient: "Open",
  clin_current_patient: "Showing now",
  exc_offline: "Pump offline",
  exc_under_target: "Under target 3 days",
  exc_night_alarms: "Many night alarms",
  exc_alarm: "Alarm now: {alarm}",
  exc_none: "No exceptions",
  clin_unavailable: "Not available from the hub yet.",

  // Portal: chart (FR-20)
  chart_title: "Delivered vs prescribed",
  range_label: "Time range",
  range_24h: "24 h",
  range_7d: "7 days",
  range_30d: "30 days",
  chart_delivered: "Delivered",
  chart_prescribed: "Prescribed",
  chart_under: "Under 90% of prescribed",
  chart_live_note: "24 h shows this session's live readings from the pump.",
  chart_show_table: "Show as a table",
  chart_col_date: "Date",
  chart_col_time: "Time",
  chart_col_alarms: "Alarms",
  chart_desc: "{days} days shown. {under} under 90% of prescribed.",
  chart_live_desc: "Live feed: {delivered} of {target} delivered.",
  chart_no_data: "No data yet.",
  chart_yes: "Yes",

  // Portal: alarm timeline
  timeline_title: "Alarm timeline",
  timeline_empty: "No alarms reported in this session.",
  timeline_active: "Still active",
  timeline_cleared: "Cleared {time}, after {minutes} min",

  // Portal: audit (FR-23)
  audit_title: "Audit trail",
  audit_col_when: "When",
  audit_col_who: "Who",
  audit_col_what: "What",
  audit_col_version: "Version",
  audit_empty: "No audit entries yet.",
  audit_who: "{name} ({role})",
  action_proposed: "Proposed",
  action_confirmed: "Confirmed",
  action_declined: "Declined",
  action_sent: "Sent to pump",
  action_active: "Active on pump",
  action_rejected: "Rejected",
  action_superseded: "Replaced",
  role_clinician: "Clinician",
  role_system: "Hub",
  role_pump: "Pump",

  // Portal: feed profiles (FR-28). Demo values only.
  profiles_title: "Feed profiles",
  profiles_intro: "Fills in the form. Demo values only, not guidance.",
  profile_overnight: "Overnight continuous",
  profile_day_bolus: "Daytime bolus",
  profile_school: "School day",
  profile_applied: "Form filled from “{name}”. Check it, then propose.",

  // Sync 2 contract additions
  error_stale_version: "A newer change was already sent to the pump, so this one cannot be confirmed.",
  exc_alarm_active: "Alarm now",
  summary_title: "Weekly summary",
  summary_range: "{from} to {to}",
  summary_delivered: "Delivered {pct}% of prescribed over {days} days.",
  summary_prior: "Previous week: {pct}%.",
  trend_improving: "Trend: improving",
  trend_steady: "Trend: steady",
  trend_declining: "Trend: declining",
  summary_under: "Days under 90% of prescribed: {count}.",
  summary_alarms: "Alarms: {count} ({list}).",
  summary_no_alarms: "No alarms this week.",
  summary_none: "No history loaded yet.",
  profiles_none: "No feed profiles for this patient.",

  users: {
    "clin-01": "Dr. Demo",
    "care-01": "Parent (demo)",
    "care-02": "School nurse (demo)",
    pump: "Pump",
    hub: "Hub",
  },
};
