export const wardCopy = {
  en: {
    map_navigation: "Ward map navigation", map_zoom: "Map zoom", zoom_in: "Zoom in", zoom_out: "Zoom out", reset_map: "Fit entire ward", demo_short: "Demo", active_alarm: "Active alarm", switch_light: "Switch to light mode", switch_dark: "Switch to dark mode",
    global: "Global", ward_map: "Ward map", patients_nav: "Patients", alerts_nav: "Alerts",
    command_center: "Care command", ward: "Pediatric ward", ward_subtitle: "Spatial overview / schematic demo layout",
    ward_floor: "Level 01", ward_unit: "Unit A", bed: "Bed", station: "Care station", corridor: "Central corridor",
    needs_review: "Needs review", connected_pumps: "Connected pumps", monitored: "Patients", selected: "Selected feed",
    all_patients: "All patients", patient_search: "Search patients or pump ID", no_matches: "No matching patients",
    no_attention: "No patients flagged for review", review_flags: "Patient review flags", roster_unavailable: "Patient roster unavailable. Check the hub connection.",
    close_details: "Close patient details", open_details: "Open patient details", patient_details: "Patient details",
    tab_monitor: "Monitor", tab_care: "Care", tab_orders: "Orders", tab_history: "History",
    feed_telemetry: "Feed telemetry", feed_active: "Active prescription", connection_details: "Connection details",
    heart_rate: "Heart rate", oxygen: "Oxygen", demo_vitals: "Demo vitals", demo_vitals_hint: "Simulated vital signs · not measured by the pump",
    live_feed: "Hub telemetry", vitals_unavailable: "Vital signs unavailable for this source", previous: "Previous", next: "Next",
    page_count: "Page {page} of {total}", map_paging: "Beds {start}–{end}", select_patient: "Select a bed to inspect its feed",
    activity_history: "Feed history", audit_tab: "Audit", delivery_tab: "Delivery", prescriptions_tab: "Prescriptions",
    show_chart: "Chart", show_table: "Table", selected_patient: "Selected patient", demo_layout: "Schematic layout",
    expand_map: "Expand map", return_map: "Return to map", all_clear: "No active pump alarms", last_signal: "Last signal",
    pump_connection: "Pump connection", alerts_count: "{count} patients flagged",
  },
  es: {
    map_navigation: "Navegación del mapa", map_zoom: "Zoom del mapa", zoom_in: "Acercar", zoom_out: "Alejar", reset_map: "Ver toda la sala", demo_short: "Demo", active_alarm: "Alarma activa", switch_light: "Activar modo claro", switch_dark: "Activar modo oscuro",
    global: "Global", ward_map: "Mapa", patients_nav: "Pacientes", alerts_nav: "Alertas",
    command_center: "Centro de cuidados", ward: "Sala pediátrica", ward_subtitle: "Vista espacial / plano de demostración",
    ward_floor: "Nivel 01", ward_unit: "Unidad A", bed: "Cama", station: "Puesto de cuidados", corridor: "Pasillo central",
    needs_review: "Requieren revisión", connected_pumps: "Bombas conectadas", monitored: "Pacientes", selected: "Alimentación elegida",
    all_patients: "Todos los pacientes", patient_search: "Buscar paciente o bomba", no_matches: "Sin resultados",
    no_attention: "Ningún paciente requiere revisión", review_flags: "Avisos de pacientes", roster_unavailable: "Lista no disponible. Compruebe la conexión.",
    close_details: "Cerrar detalles", open_details: "Abrir detalles", patient_details: "Detalles del paciente",
    tab_monitor: "Monitor", tab_care: "Cuidados", tab_orders: "Órdenes", tab_history: "Historial",
    feed_telemetry: "Telemetría de alimentación", feed_active: "Prescripción activa", connection_details: "Detalles de conexión",
    heart_rate: "Frecuencia cardíaca", oxygen: "Oxígeno", demo_vitals: "Signos demo", demo_vitals_hint: "Signos vitales simulados · no medidos por la bomba",
    live_feed: "Telemetría del centro", vitals_unavailable: "Signos vitales no disponibles", previous: "Anterior", next: "Siguiente",
    page_count: "Página {page} de {total}", map_paging: "Camas {start}–{end}", select_patient: "Elija una cama para ver la alimentación",
    activity_history: "Historial de alimentación", audit_tab: "Auditoría", delivery_tab: "Administrado", prescriptions_tab: "Prescripciones",
    show_chart: "Gráfico", show_table: "Tabla", selected_patient: "Paciente elegido", demo_layout: "Plano esquemático",
    expand_map: "Ampliar mapa", return_map: "Volver al mapa", all_clear: "Sin alarmas activas", last_signal: "Última señal",
    pump_connection: "Conexión de la bomba", alerts_count: "{count} pacientes con avisos",
  },
};
