[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -Wall
build_src_filter = +<*> -<digital_main.cpp>
lib_deps =
  256dpi/MQTT@^2.5.2
  bblanchon/ArduinoJson@^7

[env:native]
platform = native
build_flags = -std=c++11 -Wall -Wextra -DUNITY_INCLUDE_DOUBLE
build_src_filter = +<prescription.cpp> +<pump_controller.cpp> +<digital_main.cpp>
lib_deps = bblanchon/ArduinoJson@^7
test_build_src = yes
test_framework = unity
